name: Update Bird of the Week

on:
  schedule:
    - cron: '0 13 * * 0'  # Sundays 8 AM EST (1 PM UTC)
  workflow_dispatch:

jobs:
  update-bird:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('update_bird.py') }}

      - name: Install dependencies
        run: pip install pandas numpy

      - name: Run Python script
        run: python updated_bird.py

      - name: Commit update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add bird_of_the_week.txt
          git commit -m "Weekly bird update [skip ci]" || echo "No changes"
          git push
